#!/usr/bin/env python3
# -*- mode: python -*-

import sys
import json
from pathlib import Path

if len(sys.argv) != 4:
    print("Usage: get-internal-tool <metadata_location> <tool_name> <tool_type>")
    sys.exit()

meta_loc = Path(sys.argv[1])
name = sys.argv[2]
tool_type = sys.argv[3]

try:
    meta = json.load(open(meta_loc / "meta.json"))
except Exception as exc:
    print(f"Failed to load tool metadata: {exc}")
    sys.exit()

if tool_type not in ["persistent", "transient"]:
    print(f"Tool type must be persistent or transient, cannot be: {tool_type}")
    sys.exit()

if name not in meta[tool_type].keys():
    name = name + "-" + tool_type
    if name not in meta[tool_type].keys():
        print(f"{name} is not an existing tool option")
        sys.exit()

print(name)
